### ISSUE TITLE
Almost unplayable sometimes.

### ISSUE THREAD

**Issue by MintyJuulyPodeqeq** [muskit/H3VR-TNH-Quality-of-Life-Improvements#1]
basically i can see in the config on h3vr that tnh qol improvments is constantly trying to refresh and get a number for the number of online people or list of leaderboards. It almost BREAKS the game and makes it unplayable for me atleast. PLEASE remove the leader board feature and just use the one thats in the base game.

**Comment by muskit** [comment]
If the player count feature is causing issues you can disable it in your mod manager's Config Editor. That should prevent it from loading in.

If you don't mind, to help me figure out why there's issues:
1. What version of the game are you running? Is it experimental or mod-safe?
2. What happens exactly thats makes the game unplayable?
3. (edit): Do you have TNHTweaker installed?
4. What version of the mod are you running?

**Comment by muskit** [comment]
The issue you're experiencing might actually be from TNHTweaker if it's installed. At the time the issue was created, TNHTweaker only worked on the experimental non-mod-friendly branch.

**Comment by MintyJuulyPodeqeq** [comment]
Hey,
Yea I just did that through the config thank you I really appreciate it, but I’m running the mod friendly branch, and what happens is that let’s say you’re playing tnh, running around and youll get an initial stutter, and slowly it’ll get worse and worse and for longer periods of time and I look at the belpn config and I see nothing whatsoever just the bullet code being fired off that’s it. So essentially the config doesn’t specify what’s happening and I continue to lag for so long 


Sent from Yahoo Mail for iPhone


On Wednesday, March 30, 2022, 11:21 AM, msk ***@***.***> wrote:




If the player count feature is causing issues you can disable it in your mod manager's Config Editor. That should prevent it from loading in.

If you don't mind, to help me figure out why there's issues:
   
   - What version of the game are you running? Is it experimental or mod-safe?
   - What happens exactly thats makes the game unplayable?

**Comment by muskit** [comment]
Hmm, my mod does nothing to bullets or shooting mechanics. My leaderboard
code simply scans some data that the game sets, not touching it at all.

Try disabling this QoL mod completely and see if the problem still persists.

**Comment by muskit** [comment]
Check your other mods, I tested on mod-safe with and without TNHTweaker (looks like it works on mod-safe now) and have no issues. Make sure everything's up to date. If you have still have further issues and suspect it's due to this mod, please reply with log as follows:
1. Make sure game is closed
2. In r2modman, go to Settings > Debugging tab.
3. Click "Copy log file contents to clipboard"
4. Paste into a comment here.

Additionally, please list all mods you have installed.

**Comment by muskit** [comment]
As it has been over a week since the last reply, I will close this issue. AFAIK this mod has no fatal issues that make Take and Hold unplayable.
