### ISSUE TITLE
Not working with Atlas-based maps

### ISSUE THREAD

**Issue by O-Deka-K** [muskit/H3VR-TNH-Quality-of-Life-Improvements#2]
I like this mod a lot and find it quite useful. However, none of the wrist menu additions appear when using any TNH maps that are based on Atlas. The supply panel counters do appear, and the message beside the high score table about it being disabled when using TNHTweaker also appears.

This happens on Aporkalypse Now, Shortscope TnH, Department of Meat, and Factory Take and Hold. I've also tried making a new r2modman profile with just Atlas maps and TNH QoL Improvements, with the same result. Since Atlas and MeatKit are both by [H3VR Modding](https://github.com/H3VR-Modding) (nrgill28), I wonder if they could help?

TNH Quality of Life Improvements version 1.2.3
H3VR Update 110a5, alpha - Mod Safe branch
Valve Index HMD
r2modman 3.1.42

**Comment by muskit** [comment]
Confirmed, looking into it. Others have had similar issues in the past but never thought it might have something to do with Atlas.

**Comment by O-Deka-K** [comment]
Working great! Thank you.
