### ISSUE TITLE
Supply Points Unable to generate loot  

### ISSUE THREAD

**Issue by Patch276** [muskit/H3VR-TNH-Quality-of-Life-Improvements#3]
I have recently begun playing H3VR again, and when I use this mod one of two things happens:

1) The main features of the mod, the hold number and override token count, do not appear on my radar hand despite being set to in the config file. The health gem will still flash or show the circle timer as set, and the supply point will still display a number on the item being purchased.  

2) If I turn off and turn back on the hold counter and token counter they will become functional again, but a new issue begins. After doing this any time I buy an item at a supply point it will not spawn, and will lock the supply point screen as I assume it tries to find an item to spawn.  

When I look at the black log screen the H3VR generates while playing it will infinitely spawn one of two messages depending on the map I am playing at the time 

1)
tnh manager is null

2)
[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: WurstMod.Shared.Extensions.ReflectSet (UnityEngine.Object,string,object) <0x00153> WurstMod.Runtime.Patch_LegsUpdate_MoveToPoint.Prefix (FistVR.Sosig) <0x005ef> (wrapper dynamic-method) FistVR.Sosig.DMD<FistVR.Sosig..LegsUpdate_MoveToPoint> (FistVR.Sosig) <0x00047> FistVR.Sosig.LegsUpdate () <0x0006b> FistVR.Sosig.Update () <0x00236>

After this began I tried to fully delete both H3 and all mods then reinstall them. Even after this it just put me back to half the mod not functioning. If I disable this mod specifically the supply points go back to generating loot as normal Please let me know what information I can provide to help get this issue fixed. This is one of my favorite mods and I hope to be able to use it again soon!

**Comment by muskit** [comment]
1. What other mods are you running with?
2. If you disable *just* this mod, does TNH return to normal?
3. What beta branch are you playing on?

Unless my mod broke something else not mentioned here, the second error seems to do with something breaking enemy AI, which my mod doesn't touch

**Comment by Patch276** [comment]
2. Yes, with the set of mods on this profile by disabling only this mod the issue is resolved. I also tried making a new profile in the mod manager with only  TNH_QOL_Improvments and TakeAndHoldTweaker added in case that was the conflict and it ran just fine 

3. In steam I have my beta branch set to 'none' 

I'm fairly certain that there is a conflict somewhere, but I have no idea what mod could be causing it and i was hoping to avoid brute forcing through 100 ish mods to find it. If you don't see anything in my list that totally fine, but any advice on which mods you think may be causing the conflict would be greatly appreciated.

1. My Mod List:

BepInExPack_H3VR by BepInEx
Sodalite by nrgill28
TNH_Quality_of_Life_Improvements by muskit
Stratum by Stratum
Mason by Stratum
Deliter by Stratum
Deli by DeliCollective
WurstMod by nrgill28
IslandCompound by devyndamonster
JM_Monolith_2 by JoshMate
Costa_con_Carne_TaH by NunSuperior
Atlas by nrgill28
Aporkalypse_Now by Marcel
Promeatheus_TaH by NunSuperior
BlackHawkDownTNH by Abass20
CairoStation by CirnoPortsMaps
Hotel_Hotlink by sirpotatos
Franktory by stark
JungleCampTNH by Abass20
Rostok_TnH by Nikpo
JungleValleyTNH by Abass20
Factory_Take_and_Hold by calafex
MagazinePatcher by devyndamonster
TakeAndHoldTweaker by devyndamonster
PMCPete by devyndamonster
OtherLoader by devyndamonster
Doomboxs_German_Uniforms by Doombox3
Stalker_Sasha by Vohnyshche
Looting_Larry by Fez3557d4428b7f48fa
SilentSully by OsaPL
OpenScripts2 by cityrobo
FTW_Arms_AFCL by Andrew_FTW
PuppyScripts by Arpy
Potatoes_TNH_BGM_Loader by Potatoes
XUnity_ResourceRedirector by bbepis
H3VR_Sideloader by denikson
MonoMod_Loader by BepInEx
HookGenPatcher_H3VR by nrgill28
OpenScripts by cityrobo
H3VRUtilities by WFIOST
TOZ66 by Vohnyshche
TOZ34 by Vohnyshche
SIG_Sauer_P220 by Vohnyshche
Meats_ModulShotguns by Meat_banono
ModulAK_Plus by Not_Wolfie
PKM_2 by JerryAr
TNH_BGM_Cheeki_Breeki_Hardbass_Remiks by ValhallaMods
Meats_ModulAK by Meat_banono
BINGUS_Shotguns by Chargin
Modul_VAL by Not_Wolfie
Ashes_Groza_Remake by fsce
FTW_Arms_AN94 by Andrew_FTW
Stalker_Bandit_Voices by Vohnyshche
Monolith_Sosig_Voices by Vohnyshche
SVU_A by devyndamonster
PBPISTOL by superpug
OTs_02_Kiparis by devyndamonster
MrCalhouns_Clear_Sky_Battle_at_Yantar by Vohnyshche
Firelake_Fighting_Unknown_TNH_BGM by Vohnyshche
Uzicko_Kolo_TNH_BGM by Vohnyshche
Stalker_Zombie_Voices by Vohnyshche
FN_F2000 by edisleado
modulSVD by nayr31
Walther_P99 by Muzzle
Stalker_Modpack by Vohnyshche
30mm_Mounts by fsce
Swift_Suspenders_by_Arpy by Arpy
Meats_ModulARpt2 by Meat_banono
Modern_Warfighter_Foregrips by Andrew_FTW
Modern_Warfighter_Rails by Andrew_FTW
Modern_Warfighter_Lights_and_Lasers by Andrew_FTW
ModernWarfighterRemake_Optics by fsce
65Grendel by Arpy
Andrews_Lively_Lederhosen by Andrew_FTW
Meats_ModulAR by Meat_banono
Meats_ModulSIG by Meat_banono
Modul_FAL by Not_Wolfie
MP443_Grach by Not_Wolfie
FTW_Arms_Modern_Warfighter_Remastered by Andrew_FTW
Modul_AR9 by Not_Wolfie
FTW_Arms_Modular_Vector by Andrew_FTW
FTW_Arms_Modular_M1a by Andrew_FTW
FTW_Arms_VPO215 by Andrew_FTW
FTW_Arms_Modular_Addons by Andrew_FTW
Meats_ASh12 by Meat_banono
SR1MP by nayr31
Ashes_KelTec_RFB by fsce
FTW_Arms_KS_23 by Andrew_FTW
FTW_Arms_Modular_Helmets by Andrew_FTW
FTW_Arms_Nightvision by Andrew_FTW
VeprHunter by nayr31
Modul_M700 by Not_Wolfie
ModulTT by superpug
Meats_Rigs by Meat_banono
Magazine_fed_Classic_SKS_Kit by Arpy
FTW_Arms_Mk18_Mjolnir by Andrew_FTW
GoldenTT by nayr31
PMC_Pete_Content by devyndamonster
PrefabReplacer by cityrobo
Meats_ModernWarfighterOptics by Meat_banono
TNH_Announcer_Lois_NEXT by Sora101Ven
Cyberpsychosis_TnH_Theme by Hani
MeloncorpBoxes by MelonCorp
MercMelon by MelonCorp
Looting_Larry_MooseEdit by MooseOnTheLoose
Wristimate by AshHat
BackpackHarnessEnabler by cityrobo
SpectatorPreconfigurator by cityrobo
BetterHands by MaiqTheDude
LSIIC by BlockBuilder57
BepInEx_ConfigurationManager by BepInEx
SosigRipper by OsaPL
Better_Bullet_Cracks by Shampooh
BetterGrapplingGun by cityrobo
Alternate_Whoosh by Shampooh
BulletKinesis by OsaPL

**Comment by muskit** [comment]
Send me your profile code so I can replicate your mods list on my end, and I don't miss a mod if I end up trying to manually install.
![image](https://github.com/muskit/H3VR-TNH-Quality-of-Life-Improvements/assets/15199219/e6867f1d-8712-414e-adf2-e63a33aa60ab)

**Comment by O-Deka-K** [comment]
I can add to this. After you fixed the mod for Atlas-based maps, it stopped working for WurstMod-based maps. I've tried it again with a new profile that contained only JM Monolith 2, Wurst City Reloaded Day, Island Compound and TNH QoL Improvements. The symptoms are the same as in Issue #2.

TNH Quality of Life Improvements version 1.2.4
H3VR Update 110a6, alpha - Mod Safe branch
Valve Index HMD
r2modman 3.1.42

**Comment by Patch276** [comment]
Before I send the profile I've found a reliable way to reproduce it.  Pretty much as @O-Deka-K said any non vanilla map disables the hold number and token count even if they're the only mods added to a profile with dependencies. 


Simplified Profile Code : 0189aa79-7c97-4d13-f90c-682ba35db270

When using the Prometheus map you mod would stop working fully, but with either of the default maps it worked as expected

**Comment by Patch276** [comment]
As for the initial issue I mentioned with the loot not spawning I was using this profile ( 0189aa7c-ce86-a9cc-849c-1165b7944055 )

Playing as PMC Pete
Map Prometheus

This issue is resolved whenever your QOL mod is disabled

**Comment by muskit** [comment]
As of commit 611f074b73b0c76d0f5da72b970b4375e5fa6899 (**release 1.2.5**), everything should be initialized properly now in three map types (standard, Atlas, and WurstMod). I was able to finish a game in each tested map type on my end.

Thank you for helping me track down the issue!

**Comment by O-Deka-K** [comment]
Awesome. Thanks again!

**Comment by Patch276** [comment]
Haven't had a single issue since thank you for being so quick to put out an update!
